### ISSUE TITLE
Topics navigation broken

### ISSUE THREAD

**Issue by meskilla** [goggle/script.module.srgssr#17]
Hello, all SRF addons no longer allow to navigate through the "Topics" entry. "Show by date" and "All shows" still work fine from what I checked.

Without the "Topics" section it's impossible to find the livesport streaming events. I believe you can still stream them if you grab the event number from the website and create an strm file from it yourself.

edit: forgot to mention this is happening on Nexus, did not test against Kodi Matrix anymore.

**Comment by goggle** [comment]
Thanks for reporting this.
The `Homepage` menu is broken as well. I will have a look.
