### ISSUE TITLE
Live TV does not work anymore because of DRM protection

### ISSUE THREAD

**Issue by goggle** [goggle/script.module.srgssr#2]
Since December 2018, it is not possible to play live TV on any SRG SSR related Kodi plugins (e.g. `plugin.video.srfplaytv`). This is due to recently added DRM protection of the live streams:

- https://www.srf.ch/sendungen/hallosrf/weshalb-funktioniert-der-livestream-auf-srf-ch-nicht-mehr
- https://rtsr.ch/digitalrightsmanagement/
- https://www.rsi.ch/chi-siamo/mestieri/La-SSR-introduce-la-codifica-digitale-11038056.html

Kodi 18 (Leia) has received some sort of DRM support (have a look at the Kodi's Python documentation here: https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcdrm.html). So I guess it might be possible to bring Live TV playback back to my plugins (definitely not for Kodi 17, but possibly for Kodi 18).

Can someone with knowledge in this topic approve this?
How exactly can this be done? If someone can help, please let me know.

The protected streams which I'm talking about, can be found here: https://www.srf.ch/play/tv/live/

**Comment by claudep** [comment]
Maybe take some inspiration from the Netflix plugin?
https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/MSLMediaDrm.py

**Comment by goggle** [comment]
I don't think we really need Live TV support for the plugins, there already is the excellent `pvr.zattoo` .
But it would be nice to add support for web-only live streams (mainly sport events). I think these are not even DRM protected.

**Comment by goggle** [comment]
#14 brings back support for web-only live streams.
For live TV I suggest to use `pvr.zattoo` and won't support it in this plugin.
