### ISSUE TITLE
Show by date empty

### ISSUE THREAD

**Issue by campipaolo** [goggle/script.module.srgssr#24]
Hello guys!
I'm running on Linux Mint 21 amd64 with kodi 20.2 and addon v.  2.2.3 
Section show by date is empty, maybe something in chamged on web site structure 
If necessary for you debug, I'll upload a log file

Thamks for your job!

**Comment by goggle** [comment]
Hi, thanks for reporting your issue.
I have just checked it by myself, and it still seems to work fine for SRF and RTS, but not for RSI.
I assume you are using the RSI plugin, correct?

**Comment by campipaolo** [comment]
> Hi, thanks for reporting your issue. I have just checked it by myself, and it still seems to work fine for SRF and RTS, but not for RSI. I assume you are using the RSI plugin, correct?

Correct!

**Comment by goggle** [comment]
Ok, so I have investigated this issue and it seems like RSI has removed the links to the actual episodes in their TV guides.
See for example here: https://www.rsi.ch/play/tv/guida-programmi/2023-09-14
![image](https://github.com/goggle/script.module.srgssr/assets/1856425/40891fc8-11f0-47e9-8a1d-d5f684f1049d)
The videos which are playable in the media library have these red play buttons for all the channels (SRF 1, RTS 1, etc.) except for LA 1 and LA 2...
Unfortunately there is not much I can do as long as I don't have these links to the actual content...

**Comment by campipaolo** [comment]
> Ok, so I have investigated this issue and it seems like RSI has removed the links to the actual episodes in their TV guides. See for example here: https://www.rsi.ch/play/tv/guida-programmi/2023-09-14 ![image](https://user-images.githubusercontent.com/1856425/268397128-40891fc8-11f0-47e9-8a1d-d5f684f1049d.png) The videos which are playable in the media library have these red play buttons for all the channels (SRF 1, RTS 1, etc.) except for LA 1 and LA 2... Unfortunately there is not much I can do as long as I don't have these links to the actual content...

tnaks anyway for your support

**Comment by goggle** [comment]
@campipaolo What you could do is to write an email to the RSI support team and ask them why they don't provide the links to the actual content in the TV guide overview (maybe add such a screenshot, so they understand the issue immediately).

**Comment by campipaolo** [comment]
> @campipaolo What you could do is to write an email to the RSI support team and ask them why they don't provide the links to the actual content in the TV guide overview (maybe add such a screenshot, so they understand the issue immediately).

all things come back works well! Without mail....
Issue Closed
