### ISSUE TITLE
browsing the main menu no longer works with all the play addons

### ISSUE THREAD

**Issue by meskilla** [goggle/script.module.srgssr#27]
I believe it happend two days ago? Now kodi throws out 
errors in the build_main_menu function.

creating a strm playlist file with
plugin://plugin.video.srfplaytv/?mode=50&name=urn:swisstxt:video:srf:$id
syntax still works

I checked it against all the play addons the error is the same.

**Comment by DenTheBarde** [comment]
I have created a pull request for my error: Error Contents: module 'xbmc' has no attribute 'translatePath'. On my PC this fixed the issue with loading the menu/ directory.

It appears, translatePath was removed and moved to xbmcvfs. Not sure if this is also your underlying issue.

**Comment by goggle** [comment]
Thanks @meskilla for reporting the issue and @DenTheBarde for suggisting a PR. I'll into it in the next days.

**Comment by goggle** [comment]
For some reason, I have never encountered this error, but I have accepted the PR from @DenTheBarde and released a new version 2.2.4. If https://github.com/xbmc/repo-scripts/pull/2595 gets accepted, I will release version `2.2.4` of `plugin.video.srfplaytv`, `plugin.video.rtsplaytv`, `plugin.video.rsiplaytv` and `plugin.video.swiplaytv`.
