### ISSUE TITLE
please release PR from tobiaswaldvogel into offical Kodi repo

### ISSUE THREAD

**Issue by GETandSELECT** [goggle/script.module.srgssr#7]
Hey

He released a *.zip thats working:
https://github.com/tobiaswaldvogel/script.module.srgssr/archive/v1.8.0rc1.zip but I prefer to install from official sources.

It would be great if you push/release the changes into a version bump from you.

thanks

**Comment by eflavio** [comment]
Hi,
Is there any update? The changes of  @tobiaswaldvogel do not seem to be released here. Also, the the zip file is no longer accessible...

**Comment by Flo3561** [comment]
Hi there,
Does anybody have an update on that PR?

**Comment by claudep** [comment]
@goggle, are you still interested in maintaining this module? Whatever your response, I think having several maintainers should be ideal. If needed, I would be glad to help.

**Comment by goggle** [comment]
Version 2.0.0 is now in the official Kodi addon repository. Thanks to everyone who has contributed!

@claudep I'm happy to add more maintainers to the project. But first start with by submitting a PR. If someone wants to work on this addon, tell me what you want to do (e.g. by opening an issue) and submit a PR afterwards.

**Comment by claudep** [comment]
I see with pleasure that development regain some strength! I'm currently not using my Vero 4k device, so also a bit less motivated to contribute right now.
